
function new_vertex = getNewAuxRRTVertex(closest_vertex, new_random_point, vertex_length)

    new_vertex(1) = closest_vertex(1) +...
        (new_random_point(1) - closest_vertex(1))/...
        norm((new_random_point' - closest_vertex'))*...
        vertex_length;
    
    new_vertex(2) = closest_vertex(2) +...
        (new_random_point(2) - closest_vertex(2))/...
        norm((new_random_point' - closest_vertex'))*...
        vertex_length;
    
    new_vertex(3) = 0;
    % .1*atan2(new_vertex(2), new_vertex(1));
    
    new_vertex = new_vertex';
    